Match the landing page (about us section) with Figma
TechPlus-UW/Portal-FE pull request #89
Opened 2021-02-05 01:48 UTC by kerry918

Change the about us section to match the Figma, and added a linear gradient background without the curve. 

Close https://github.com/TechPlus-UW/Portal-FE/issues/81

2021-02-05 04:58 UTC, JamesCahyadi requested changes
Left a few small suggestions for cleanup. Otherwise looks good!

2021-02-05 04:58 UTC, JamesCahyadi commented on src/components/landing_page/Content.js
> +        <Grid item xs={12} sm={12} md={7}>
There's no need to add sm={12} here and the other places below this since you already have xs={12}. (Similar to how you don't need to specifiy lg={7} and xl={7} since you already have md={7}.)

2021-02-05 04:58 UTC, JamesCahyadi commented on src/components/landing_page/Content.js
> +        <Grid item xs={12} sm={12} md={6} className={classes.pic2}>
I think remove the pic2 class because it doesn't exist

2021-02-05 04:58 UTC, JamesCahyadi commented on src/components/landing_page/Content.js
> +      {/* <Background/> */}
delete comment

2021-02-05 04:58 UTC, JamesCahyadi commented on src/components/landing_page/Content.js
>            <h2 className={classes.vision}>Vision</h2>
Maybe reduce the spacing here to match the figma more
![image](https://user-images.githubusercontent.com/45665593/106991638-a9415400-6744-11eb-9fdc-ec6785445014.png)

2021-02-05 23:27 UTC, JamesCahyadi approved these changes

2021-02-07 19:11 UTC, jack-lin-jql commented
Sorry for the late comment review. 
On the responsiveness note, a few things:
1. For the text vertical alignment, can we vertically align to the middle instead of the top for both vision and mission? 
![image](https://user-images.githubusercontent.com/13803465/107156550-fabc2f80-694c-11eb-86d5-d11554263382.png)

Please check if there is any out of the box prop config to achieve this, if not the following will work:

We can do a display flex and justify content on the container divto make that happen: 
![image](https://user-images.githubusercontent.com/13803465/107156694-d745b480-694d-11eb-87a9-d91eb3b4f47a.png)

2. When the page is shrunk to a small width, can we center align the pictures? 
![image](https://user-images.githubusercontent.com/13803465/107156733-170c9c00-694e-11eb-8b1b-86a5a9cfcecd.png)

Please check if there is any out of the box prop config to achieve this, if not the following will work:

This can also be achieved with flexbox: 
![image](https://user-images.githubusercontent.com/13803465/107156786-576c1a00-694e-11eb-9cc1-a0b1cefa714f.png)

2021-02-07 19:21 UTC, jack-lin-jql requested changes

2021-02-07 19:21 UTC, jack-lin-jql commented on src/components/landing_page/Content-jss.js
> +
Please don't commit this into the master branch as it's not being used

2021-02-07 19:21 UTC, jack-lin-jql commented on src/components/landing_page/Event-jss.js
> +    color: "#020B2C",
what is this for?

2021-02-07 19:21 UTC, jack-lin-jql commented on src/components/landing_page/Content-jss.js
> +  pic: {
nit: would make this naming more specific to ensure no future css naming collisions

2021-02-07 19:22 UTC, jack-lin-jql commented
Left some comments, otherwise, looks good!

2021-02-09 16:22 UTC, jack-lin-jql approved these changes
LGTM

2021-02-09 16:23 UTC, jack-lin-jql approved these changes
LGTM

2021-02-09 19:36 UTC, merged